### ISSUE TITLE
Output Readme file content fails because readme file does not exist

### ISSUE THREAD

**Issue by martijndohmen** [YannickRe/azuredevops-buildagents#10]
![image](https://user-images.githubusercontent.com/38530076/128590639-d5d83556-b8da-4cc6-92ab-1b135b86ee94.png)

The path looks correct, but the file isn't copied over i guess.

**Comment by Marcus-James-Adams** [comment]
Are you running this on a Linux build agent?  Iirc I have to change the
filename to be Readme.md as Linux is case sensitive

**Comment by martijndohmen** [comment]
Thnx @Marcus-James-Adams the issue is solved.
