### ISSUE TITLE
Post-generation scripts

### ISSUE THREAD

**Issue by aleqsss** [YannickRe/azuredevops-buildagents#11]
I have a question, how do you run the post-generation scripts which are mentioned as part of the image generation?
https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md#post-generation-scripts

Thank you for an inspiring repository!

**Comment by YannickRe** [comment]
I don't run them... To be completely honest and transparent: I forgot about them when I finally got it working 😀.
My builds run without an issue so I am unsure how necessary they are.
