### ISSUE TITLE
GithubFeedToken

### ISSUE THREAD

**Issue by MathiasVandePol** [YannickRe/azuredevops-buildagents#13]
Hey Yannick,

I noticed you require a github_feed_token parameter to be set.
Is this still required? There was a commit in the official virtual-environments repo some time ago which removed the requirement:

https://github.com/actions/virtual-environments/pull/3191/commits/4462c5bd4cfe62e065b2a8f9e680a874187aa0ac

**Comment by YannickRe** [comment]
Removed the GitHub token from the scripts, with https://github.com/YannickRe/azuredevops-buildagents/commit/338ea945efb2861daa04c07f45f5c846cd64357c
