### ISSUE TITLE
Issue update in the VMSS disk size mismatch

### ISSUE THREAD

**Issue by trhumphries** [YannickRe/azuredevops-buildagents#24]
Ubuntu builds just fine. On Windows after the image is built where it tries to replace it I get:
Message: The specified disk size 86 GB is smaller than the size of the corresponding disk in the VM image: 256 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size.

I don't see anyplace in the scripts where is specifies disk size any ideas?

**Comment by YannickRe** [comment]
I'm sorry, I have never seen that before. Could you tell me which Windows version you are building and what the specs of your VMSS are (which sizing did you pick)?
Have you tried running the script yourself, separately afterwards? The generated VHD should still be there, so you can try swapping it in the VMSS yourself.

**Comment by trhumphries** [comment]
Strangely when I run the replace from a command line it works just fine
