### ISSUE TITLE
The term 'packer' is not recognized as the name of

### ISSUE THREAD

**Issue by ronaldvdvelden** [YannickRe/azuredevops-buildagents#26]
Hi,

I am having trouble using you're devops pipeline.

It fails saying the term packer is not recognized. I know it's there because in the previous step I installed it. And that also proves it is already installed

![image](https://user-images.githubusercontent.com/46248573/203820351-b623d7f9-2f4a-4f53-873a-7f2adf1f8cde.png)

Do you have any idea?

![image](https://user-images.githubusercontent.com/46248573/203819654-f15c5431-384f-4406-828b-d4e5327e441a.png)

Thanks,
Ronald

**Comment by YannickRe** [comment]
Hmm. I assume you are not using a Microsoft Hosted Agent for your first run?
Could it be that Packer is installed on your build agent, but not added into the PATH and thus cannot be found by PowerShell?

**Comment by ronaldvdvelden** [comment]
Hi Yannick,

sorry forgot to reply. I solved it by using a local build agent. Worked as a charm

thanks for sharing this code
