### ISSUE TITLE
Please clean up this repo, the resources which are no longer in use and wont be used in future as well, this would make this repo more readable

### ISSUE THREAD

**Issue by rajeevoncloud9** [YannickRe/azuredevops-buildagents#27]
Thanks :)

**Comment by YannickRe** [comment]
All the files in the repo are in use, I have no clue what you mean. Feel free to create a PR with your suggestions, and I will evaluate it.
Just a statement like yours helps no one, so please be constructive in your feedback.

**Comment by rajeevoncloud9** [comment]
I am extremely sorry if it bothered you. Just wanted to make sure that everything is in use.
Thank you ver much for the prompt response.

**Comment by rajeevoncloud9** [comment]
confirmed
