### ISSUE TITLE
Issue with run_validation_diskspace

### ISSUE THREAD

**Issue by TobiasLaving** [YannickRe/azuredevops-buildagents#28]
The VNET commit seems to have broken something for me:
```
Syntax-only check passed. Everything looks okay.
Show Packer Version
1.8.4
Build ubuntu2204 VM
Error: Missing expression

  on <value for var.run_validation_diskspace from arguments> line 1:
  (source code not available)

Expected the start of an expression, but found the end of the file.
```

What is the expected behavior?

**Comment by mike-f50** [comment]
I'm just trying azuredevops-buildagents for the first time and got the same error.  Having taken a branch from 18th November, it now seems to be running.

**Comment by YannickRe** [comment]
I'm sorry you are having this issue. Could you try to add following to your variables:

| Variable | Value |
|-----------------------------|-------|
| BUILD_AGENT_SUBNET_NAME | $null |
| BUILD_AGENT_VNET_NAME | $null |
| BUILD_AGENT_VNET_RESOURCE_GROUP | $null |

**Comment by mike-f50** [comment]
Thanks @YannickRe, but I'm afraid I had those already.

**Comment by TobiasLaving** [comment]
I also have these values configured.
Interesting, what packer version are you running @YannickRe ?
I guess we could have been running different commits of the underlying repo as well ( it checkout master )

**Comment by YannickRe** [comment]
I will need a three things from both of you @mike-f50 & @TobiasLaving so I can try and reproduce as close as possible:

1. Which image are you trying to build?
2. What's the OS of the build agent you are building the image on?
3. Output of the failing "Build VM step", from "Generating script" to "Build xxx VM"

This is mine:
```
Generating script.
Formatted command: . 'C:\a\1\s\azuredevops-buildagents\scripts\build-image.ps1' -ResourcesNamePrefix 9377 ` -ClientId 000-00 ` -ClientSecret *** ` -TemplatePath C:\a\1\s\runner-images\images\win\windows2019.json ` -ResourceGroup RGGroup ` -StorageAccount PackerStorage` -SubscriptionId 000-00 ` -TenantId 000-000 ` -VirtualNetworkName $null ` -VirtualNetworkRG $null ` -VirtualNetworkSubnet $null -Location westeurope
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\a\_temp\21b14626-aa86-4f31-9f27-03999c4798d1.ps1'"
Syntax-only check passed. Everything looks okay.
Show Packer Version
1.8.2
Build windows2019 VM
```

**Comment by YannickRe** [comment]
Thank you, I will check it out.

I have a bit of data already:

- Build Ubuntu 20.04 on Ubuntu 20.04 with Packer 1.8.3 works
- Build Ubuntu 22.04 on Ubuntu 22.04 with Packer 1.8.3 **doesn't work**
- Build Windows 2019 on Windows 2019 with Packer 1.8.3 works
- Build Windows 2022 on Windows 2022 with Packer 1.8.3 works

Seems as if the change mainly has an impact on Ubuntu 22.04, any chance you could test any of the other combinations on your end?

**Comment by TobiasLaving** [comment]
Aha, thanks for the investigation!
That is pretty strange, wonder what is up with that?

I will try when I get a chance

**Comment by almir0** [comment]
I'm having same error message but I'm trying to build Ubuntu 22.04 with Packer 1.7.2.

```
Show Packer Version
1.7.2
Build ubuntu2204 VM
Error: Invalid expression

  on <value for var.run_validation_diskspace from arguments> line 1:
  (source code not available)

Expected the start of an expression, but found an invalid expression token.


##[error]PowerShell exited with code '1'.
```

**Comment by YannickRe** [comment]
It seems to have something to do with the Ubuntu 22.04 being a different template format than all the others (.pkr.hcl vs .json), but I can't figure it out just yet.

**Comment by ronaldvdvelden** [comment]
Hi all,

I ran into this issue also and had a look at the ([unner-images project](https://github.com/actions/runner-images)

There is a [closed issue](https://github.com/actions/runner-images/issues/5690) which says you have to set the **RUN_VALIDATION_FLAG ** 

Are you aware of this issue?

At this moment I dont have time to try this.

**Comment by almir0** [comment]
Thanks @ronaldvdvelden 

After adding RUN_VALIDATION_FLAG to my DevOps library it started to build. It will hopefully finish without any errors.

**Comment by YannickRe** [comment]
@ronaldvdvelden Thanks for that information! I wasn't aware of all that, and adding it to my DevOps library seems to have fixed it. It wasn't necessary for the other files, only for the Ubuntu 220.04 one.

Oh well, I updated the readme and this should fix it all.
