### ISSUE TITLE
Parallel jobs

### ISSUE THREAD

**Issue by Noppey** [YannickRe/azuredevops-buildagents#29]
Hi,

First of all, great work! Helps a lot to get self-hosted builds going.

I have a question:
Is it possible to run parallel jobs on a single VM instance (vmss capacity 1)?
If so, how can I set this up?
And if not, why does the VM instance need to be a quad-core machine with so much memory, while it only runs a single job at a time?

**Comment by YannickRe** [comment]
You are welcome, great that you like my work :)

1. An agent can always run 1 job maximum. You can install the agent more than once on the same VM, but Microsoft does not recommend this: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser&WT.mc_id=M365-MVP-5003400#install
They also don't support this with automatically provisioned scale set agent VM instances, as they will only install and register 1 agent. You could create a post-instantiation script that installs & registers additional agents, and attach it to your VM Scale Set. Ever VM that would spin up in that scale set would execute the script and get multiple agents. I never did this so I can't help there.
2. The temporary VM used to build the VHD is a Standard_D4s_v4 (for Linux VM's) and Standard_D8s_v4 (for Windows VM's). You can configure your VM Scale Set with whatever size you like as long as it supports the disk size that your VHD has. I just happen to like the performance of the Standard_D4s_v4 for my agents in the company too, but it's all up to you to decide whichever fits your use case best.
