### ISSUE TITLE
Using released versions of runner images?

### ISSUE THREAD

**Issue by cengelenVW** [YannickRe/azuredevops-buildagents#44]
The pipelines in this repo use the `main`-branch version of the [runner-images repository](https://github.com/actions/runner-images) to get the scripts for the various image-types.

If I'm not mistaken this `main`-branch is where all development is happening and this is regularly being formed into a [(pre-)release](https://github.com/actions/runner-images/releases). If this is correct, wouldn't it be better to only use the released versions of the runner-images?

**Comment by YannickRe** [comment]
Your understanding is correct. And yes, it would be better and more stable to checkout the latest release of each specific image type/version. This has been on my radar for a while, but I have yet to investigate and figure out how to fetch the latest release tag for an image type and then checkout that specific tag.
The second part is easy, but the first doesn't seem that straightforward. If you have any suggestions, I'll happily take them.
