### ISSUE TITLE
Getting the following error: PlatformImageNotFound : The platform image 'xxx' is not available

### ISSUE THREAD

**Issue by Tjeerd-menno** [YannickRe/azuredevops-buildagents#45]
I've tried with all versions which are in your pipelines by default. But neither Ubuntu (20.04/22.04) nor Windows (2019/2022) work.
They all give the same error.

![image](https://github.com/YannickRe/azuredevops-buildagents/assets/7081413/edb28013-5cc3-43b2-9b49-4031bd0b8843)

I've checked the availability of the images using the Azure CLI. The sku's are available in my region.

```bash
az vm image list-skus --location westeurope --publisher MicrosoftWindowsServer --offer WindowsServer
```

The error happened during the Build VM step.

**Comment by YannickRe** [comment]
Could this possibly be your issue too? https://github.com/YannickRe/azuredevops-buildagents/issues/30#issuecomment-1516728423

**Comment by Tjeerd-menno** [comment]
Yes. That was it!  

A bit strange though.  Packer's docs clearly state that for VHD builds ZRS is supported. https://developer.hashicorp.com/packer/plugins/builders/azure/arm#storage_account_type

When building managed images only LRS is supported according to the docs.
https://developer.hashicorp.com/packer/plugins/builders/azure/arm#managed_image_storage_account_type
