### ISSUE TITLE
Unable to Customize Disk space used by the Agents

### ISSUE THREAD

**Issue by harinarayanan-muthukumar** [YannickRe/azuredevops-buildagents#49]
Before I get into my issue , a Huge thank you . Everything you did helps us a ton and it solved all the issue we were having that stopped us from not leveraging Scale set's for Azure Devops Agents . 

Everything works fantastic for us , but I am unable to find any option to customize the disk size of the Scale set agent once created , by default Ubuntu2204 comes with ~86 GB Disk and Windows  comes default with 256GB of Default OS Disk space . 

I have been trying to find a way to increase the Linux Default OS Disk size also to 256 , but not having luck finding it , Any help would be highly appretiated.

**Comment by harinarayanan-muthukumar** [comment]
Also upon some research I found that its being set in this location , was wondering if there is something we can do to customize it ? https://github.com/actions/runner-images/blob/main/images/linux/ubuntu2204.pkr.hcl

**Comment by sadhac** [comment]
Hi @YannickRe , thanks for this amazing repo and all the work put in.
Recently, I am also experiencing the same issue.

Can we increase the disk space for the Ubuntu images like this:
`- task: PowerShell@2
  displayName: 'Increase Disk Space for Ubuntu Images'
  inputs:
    targetType: 'inline'
    script: |
      If ('$(setVars.OsType)' -eq 'Ubuntu') {
        Write-Host 'Attempting to modify $(TemplatePath) to increase disk space for Ubuntu'
        
        # Example: replace disk size placeholder. Adjust this line as per your template's format.
        ((Get-Content -path "$(TemplatePath)" -Raw) -replace 'DISK_SIZE_PLACEHOLDER','NEW_DISK_SIZE') | Set-Content -Path "$(TemplatePath)"
              
        Write-Host "$(TemplatePath) modified for Ubuntu disk size"
      }
`

**Comment by YannickRe** [comment]
I also asked the question at the official repository: https://github.com/actions/runner-images/discussions/8503
They don't feel like changing it, so I will close this issue.
