### ISSUE TITLE
Breaking change coming in next pre-release for Windows 2022 

### ISSUE THREAD

**Issue by b-twis** [YannickRe/azuredevops-buildagents#59]
Hi,

I have been using this great process for some time to generate out build images for Windows 2022 and recently ran into some issues. 

It started with this error
https://github.com/actions/runner-images/issues/8149

Which was fixed on the Aug 24, under the current pre-release.

So I tried to take the pre-release branch and it generated a different error right at the start of the process. related to bad arguments.
Investigating, I found that there are changes to the parameters that are being used in the runner-images build process due to a fundamental change wi th how images are stored in Azure. 
[resource_group](https://github.com/actions/runner-images/issues/8221)

I will see if I can figure the correct arguments, but any assistance would be greatly appreciated as we currently have some version compatabilities issues on some outdated build images. 

Thanks

**Comment by YannickRe** [comment]
Thanks for informing me. I have looked into it and it will be a pretty impactful change, which might also have conflicting implementations between released, pre-released and alpha tags as well as the different OS'es and versions.
That last point will fix itself the longer we wait and MS fully switches over everything to the new way.

THey have postponed this switch for so long, that it's now a very tight deadline. I am fully committed to make this repo work again, at some point, but their strict deadline conflicts with my commitments for the coming weeks.
Please hang tight, as I am aware this might be critical for some.

**Comment by erik-de-bont** [comment]
I have update the code so that we should be able to generate runner images again. See pull request https://github.com/YannickRe/azuredevops-buildagents/pull/62

**Comment by YannickRe** [comment]
It has been merged in #63
