### ISSUE TITLE
Feature Request: Able to choose specific commit id in runner images repo

### ISSUE THREAD

**Issue by System-Admins-ath** [YannickRe/azuredevops-buildagents#67]
Microsoft often releases new version that are not able to being build successfully.
Currently last working build commit id is "8634d6512e4c137e848643d21e062ecf773d04f3" for win2022.

Could be nice to add a parameter to the pipeline to only checkout specific commit id.

**Comment by Marcus-James-Adams** [comment]
Is this why there is now an option to choose from latest or stable release?

**Comment by System-Admins-ath** [comment]
This was not the root cause, closing
