### ISSUE TITLE
need help in deploying self hosted agent 

### ISSUE THREAD

**Issue by harsh29113** [YannickRe/azuredevops-buildagents#69]
Hello,

I am new to this and would like to deploy server 2019 image for self-hosted agent in our environment.
We have enabled private endpoint on our resources so microsoft hosted agent will not work as public access is disabled so devops scripts are failing,

i have deployed image from github so have mimnimum knowledge. can someone help me deploying this in our environment from scratch. need help in building a base image then i can handle the rest of the work of creating vmss and deploy instances.

Also, want to know how can i regularly update the image. it would be really helpful if someone can jump on a remote session.

**Comment by YannickRe** [comment]
Hi! Unfortunately, this is not something that is easily resolved by "jumping on a remote session". It's a rather advanced topic, and the documentation should get you there (as it has for many people already).

If there are any specific steps you are struggling with, we are happy to help you out. A full setup in your environment however is a bit beyond the scope of an open-source, after hours, little project. If you wish for that, I can provide some paid consulting hours to do the setup for you.
