### ISSUE TITLE
Waiting for WinRM to become available - Build VM task

### ISSUE THREAD

**Issue by terratest24** [YannickRe/azuredevops-buildagents#78]
Hi Yannick,

Thank you for sharing this repo, great stuff !

When using  the variables :
_BUILD_AGENT_SUBNET_NAME
BUILD_AGENT_VNET_NAME
BUILD_AGENT_VNET_RESOURCE_GROUP_

I am seeing "Waiting for WinRM to become available" during the Build VM task.

![image](https://github.com/YannickRe/azuredevops-buildagents/assets/128470797/c2ff186b-a950-4524-a8c1-9be689fb151d)

Have you seen this before or know any options here ?

I am wondering if this is because we are not calling the following variable defined in the Runner Images packer file or should the packer image build fine with a private only IP/Isolated VNET  ?
https://github.com/actions/runner-images/blob/main/images/windows/templates/windows-2022.pkr.hcl

_variable "private_virtual_network_with_public_ip" {
  type    = bool
  default = false
}_

Many Thanks!

**Comment by YannickRe** [comment]
@terratest24 The VM should be publicly reachable, is that the case with your own VNET?
You can find more info on https://github.com/YannickRe/azuredevops-buildagents/issues/64 and https://github.com/actions/runner-images/issues/7784
