### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by A1lard** [YannickRe/azuredevops-buildagents#79]
Hi Yannick,

Thank you for sharing this repo! Very helpfull!

since a few weeks we have some issues with running pipeliens due to fill disks.
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/145670866/f1123436-64e1-4947-8c23-00c0fe408b85)

error: unable to write file *****************************/variables.tf
Updating files:  87% (1364/1554)
error: unable to write file *****************************/versions.tf
fatal: cannot create directory at '*****************************': No space left on device
##[error]No space left on device : '/agent/_diag/Worker_20240228-003108-utc.log'

Is this something you can fix or do you have any tips for me?

**Comment by YannickRe** [comment]
My project only provides you with an easier way to generate your runner agents. If they get created properly, my job is done 😆. If they fail during pipeline runs, you are better off raising an issue at https://github.com/actions/runner-images

I checked some more recent posts regarding this, maybe one of these gives you the info you need?

- https://github.com/actions/runner-images/discussions/9329
- https://github.com/actions/runner-images/issues/9344

Kind regards!
