### ISSUE TITLE
Cant build multiple images in one pipeline anymore

### ISSUE THREAD

**Issue by prashantchoudhary** [YannickRe/azuredevops-buildagents#81]
Earlier we were building both Linux and windows VMs in the same pipeline. But since the change to a stage level template, it is not working anymore as the job names have started to conflict. As a work around I have forked the Repo and I am appending the 'image_type' var to the job names. Is there a recommendation/workaround for this issue?. I can raise a PR with my changes too.

**Comment by YannickRe** [comment]
I'm sorry this has impacted you. Feel free to submit a PR that solves the conflicting names, and I'm happy to have it merged.

**Comment by prashantchoudhary** [comment]
https://github.com/YannickRe/azuredevops-buildagents/pull/82

**Comment by YannickRe** [comment]
I will validate ASAP :) Thank you!

**Comment by YannickRe** [comment]
Fixed with #82 
Thanks for the work.
