### ISSUE TITLE
Build runner-images from main branch instead of release

### ISSUE THREAD

**Issue by robbert-nlo** [YannickRe/azuredevops-buildagents#84]
Hi Yannick,

I noticed my builds were failing and tracked it down to this upstream issue: https://github.com/actions/runner-images/issues/9742. This issue appears to be fixed upstream for 2 weeks already, however my build still fails because this repo uses release tags to checkout the upstream repo. Apparently, according to [this comment](https://github.com/actions/runner-images/issues/9742#issuecomment-2076949835) and the last faq question on [this page](https://github.com/actions/runner-images?tab=readme-ov-file#faqs), that is against upstream advise.

Could you consider following upstream advise on this and start building using the main branch of the runner-images repo?

Thanks,
Robbert

**Comment by YannickRe** [comment]
We only use release tags when you go "pre-release" or "release", if you want to follow recommendation from upstream then you have to select "alpha":
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/9973962/ef4f0e8d-54bb-4ca2-95d0-5698accb3359)

That should cover your request 😆

**Comment by YannickRe** [comment]
Objectively: yes. But it will be a behavioral breaking change which we need to be careful with.
Additionally, most users of this repo have their own “base” pipeline with their own input parameters, config values for agent pools etc and those users can set their own defaults for this parameter.

**Comment by robbert-nlo** [comment]
@YannickRe I understand. The thing is, I'm running this pipeline automatically and this input parameter cannot be configured from the variable group, so that leaves me with having to patch your code. I rather avoid/minimize manual patching to stay compatible with you as upstream.

**Comment by robbert-nlo** [comment]
@YannickRe I just reread your comment, and I now understand you mean most users are using a customized `buildagent-generation.yml` with adjusted settings. I'll start doing that too.

Two comments however:
1. The fact that most users are using a customized yml is not really a strong argument against changing the default version to match upstream's recommendation. In fact, it actually limits the impact of changing the default since not a lot of people will be using the vanilla `buildagent-generation.yml` file.
2. It would be nice if the defaults could be sourced from env vars / DevOps Variable Group. That way, the use of a customized yml could be avoided altogether.

**Comment by YannickRe** [comment]
1. Impact is indeed not as big, so I made the change in the template file
2. As far as I know, it's an Azure DevOps limitation that you can't fetch this default from an Environment Variable
